USE [master]
GO
/****** Object:  Database [Moxie]    Script Date: 21/02/2018 16:58:37 ******/
CREATE DATABASE [Moxie]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Moxie', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQL2008\MSSQL\DATA\Moxie.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Moxie_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQL2008\MSSQL\DATA\Moxie_log.ldf' , SIZE = 4096KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [Moxie] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Moxie].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Moxie] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Moxie] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Moxie] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Moxie] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Moxie] SET ARITHABORT OFF 
GO
ALTER DATABASE [Moxie] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Moxie] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [Moxie] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Moxie] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Moxie] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Moxie] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Moxie] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Moxie] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Moxie] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Moxie] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Moxie] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Moxie] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Moxie] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Moxie] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Moxie] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Moxie] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Moxie] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Moxie] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Moxie] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Moxie] SET  MULTI_USER 
GO
ALTER DATABASE [Moxie] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Moxie] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Moxie] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Moxie] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [Moxie]
GO
/****** Object:  Table [dbo].[Collection]    Script Date: 21/02/2018 16:58:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Collection](
	[CollectionID] [int] IDENTITY(1,1) NOT NULL,
	[Path] [varchar](256) NOT NULL
 CONSTRAINT [PK_Collection] PRIMARY KEY CLUSTERED 
(
	[CollectionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Desideratum]    Script Date: 21/02/2018 16:58:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Document](
	[DocumentID] [int] IDENTITY(1,1) NOT NULL,
	[MediaType] [varchar](50) NOT NULL,
	[Content] [ntext] NOT NULL,
	[Path] [varchar](265) NOT NULL,
	[CollectionID] [int] NOT NULL
 CONSTRAINT [PK_Document] PRIMARY KEY CLUSTERED 
(
	[DocumentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

GO
SET ANSI_PADDING OFF
GO
USE [master]
GO
ALTER DATABASE [Moxie] SET  READ_WRITE 
GO
